- src/pages/LogIn/LogIn.module.scss
- src/pages/SplashScreen/Splash.module.scss
- 초기 로딩이 좀 느려서 애니메이션 성능 향상시켜보려고 함
-  
- 
- 글꼴, 이미지 로딩 위치 고민해봐야 할 듯
- 
- 
- 없음
- 
-  
> Fix: Enhance Performance

- src/functions/logInRequest.ts
> Fix: clientID

- src/App.tsx
- src/mock/myStations.json
-  오타 수정
- App.tsx의 stationlist 라우트 수정
- 
- 
- 
-  
> Fix some errors

- src/assets/ImageData/ItemImage.tsx
- src/pages/Settings/BackgroundSetUp.tsx
- src/pages/Settings/ProfileSetUp.tsx
- src/pages/Settings/characterSetUpTab/FaceTab.tsx
- src/pages/Settings/characterSetUpTab/ItemTab.tsx
- src/pages/Settings/characterSetUpTab/OutFitTab.tsx
- src/pages/Settings/characterSetUpTab/characterSetUptab.module.scss
- src/pages/Settings/profileSetUp.module.scss
-  1.  탭 안의 이미지 사이즈 조정
- 
- 
- 
- 
-  
> CharacterProfileSetUp

- src/assets/ImageData/FaceImage.tsx
- src/assets/ImageData/ItemImage.tsx
- src/interfaces/Interfaces.ts
- src/pages/Settings/CharacterSetUp.tsx
- src/pages/Settings/ProfileSetUp.tsx
- src/pages/Settings/characterInfo/CharacterInfo.tsx
- src/pages/Settings/characterSetUpTab/FaceTab.tsx
- src/pages/Settings/profileSetUp.module.scss
- src/store/useCharacterStore.ts
- 이미지 서버에서 불러오게 변경 
- 얼굴 -> 캐릭터, 표정 -> 얼굴 변경
- 생년월일 입력 변경
- 캐릭터 인터페이스 characterAge: number -> Date|null 로 변경
- 
- 이름 입력 시 "Electrical Safety" 적용 안됨
- 
- 
-  
> 캐릭터 설정 마무리

- src/functions/fetchRequest.ts
- src/functions/logInRequest.ts
- fetchRequest 함수 예외처리 수정
-  
- 
- 
- 
- 
- 
- 
-  
> Fix: fetchRequest

- src/functions/logInRequest.ts
- src/pages/Home/MyStar.module.scss
- src/pages/Home/MyStar.tsx
- src/pages/LogIn/NaverLogin.tsx
- src/store/useCharacterStore.ts
- 함수 고침
- 홈화면에서 onboarding으로 조건없이 리다이렉트 되는거 고침
- 
- 
- 
- 
- 
- 
-  
> Fix: functions

- src/store/authStore.ts
- src/store/useCharacterStore.ts
> Fix: error1

- src/pages/LogIn/NaverLogin.tsx
- 네이버 로그인 버벅임 수정 fetchRequest 함수 수정
-  
- 
-
- 
- 
-
- 
-  
> Feat: NaverLogIn

- src/functions/logInRequest.ts
- src/pages/LogIn/LogIn.tsx
- 로그인 함수 수정
-  
- 
- 로그인 안됨
- 
- 
- 
- 
-  
> Fix: LogInRequest and LogIn

- src/types/types.ts
> Fix: add Method

- src/pages/CharacterSettings/characterInfo/CharacterInfo.tsx
-  테스트로 캐릭터 설정 마지막 페이지에 완료 버튼 추가해서 이미지 생성 하고 서버에 보내도록 해봤음.
- 
- 
- 
- 
-  
> 70 connect server

- src/assets/StationCreate/slash.svg
- src/assets/StationCreate/slideBoxShowupArrow.svg
- src/pageLayout/BottomBar.tsx
- src/pages/FriendsTab/ShowFriendRequestsList/ShowFriendRequestsList.module.scss
- src/pages/Home/Home.tsx
- src/pages/Report/ReportModal/ReportModal.module.scss
- src/pages/SearchUsers/SearchResults/ShowSearchedUser/ShowSearchedUser.module.scss
- src/pages/Station/CreateStation/CreateStation.module.scss
- src/pages/Station/CreateStation/CreateStation.tsx
- src/pages/Station/CreateStation/CreateStationBackground/CreateStationBackground.module.scss
- src/pages/Station/CreateStation/CreateStationBackground/CreateStationBackground.tsx
- src/pages/Station/CreateStation/CreateStationInfo/CreateStationInfo.module.scss
- src/pages/Station/CreateStation/CreateStationInfo/CreateStationInfo.tsx
-  정거장 생성 화면 완성
- 
- 
- 
- 
-  
> 90 create station page

- src/functions/fetchRequest.ts
- src/functions/logInRequest.ts
- src/pages/Home/Home.tsx
- src/pages/LogIn/NaverLogin.tsx
- src/pages/LogIn/Pending.module.scss
- src/pages/LogIn/Pending.tsx
> Feat: fix login

- src/pages/Station/CreateStation/CreateStationInfo/CreateStationInfo.module.scss
- src/pages/Station/CreateStation/CreateStationInfo/CreateStationInfo.tsx
- src/pages/Station/ShowStationsList/ShowStationList.tsx
- src/pages/Station/Station.tsx
> Feat: design modify complete

- src/functions/fetchRequest.ts
- src/functions/getUserInfo.ts
- src/pages/Home/Home.tsx
- src/pages/LogIn/KakaoLogin.tsx
- src/pages/LogIn/NaverLogin.tsx
- src/types/types.ts
> ssibal login

- src/App.tsx
- src/functions/logInRequest.ts
- src/interfaces/Interfaces.ts
- src/pages/Home/Home.tsx
- src/pages/Home/MyStar.tsx
- src/pages/LogIn/KakaoLogin.tsx
- src/pages/LogIn/NaverLogin.tsx
- src/pages/LogIn/Pending.tsx
- src/pages/SplashScreen/Logo.tsx
- src/pages/SplashScreen/Splash.tsx
- onboarding으로 자동이동
- pending화면 이쁘게~~ 바꿈
- 
-
- 
- 
-
- 
-  
> 105 loginfinal

- src/pages/LogIn/NaverLogin.tsx
- src/pages/PageManagement/AuthHandler.tsx
-  dskl
-  
- 
- 
- 
- 
- 
- 
-  
> 116 bugfix

- src/pages/CharacterSettings/BackgroundSetUp.tsx
- src/pages/CharacterSettings/CharacterSettings.tsx
> 118 background

- .github/workflows/build-deploy.yml
- src/pages/CharacterSettings/BackgroundSetUp.tsx
- src/pages/CharacterSettings/characterInfo/CharacterInfo.tsx
- img_maker url 수정
-  
- 
- -
- 
- 
- 
- 
-  
> Fix:imgmaker

- src/pages/SearchUsers/SearchResults/SearchResults.module.scss
- src/pages/SearchUsers/SearchResults/SearchResults.tsx
- src/pages/SearchUsers/SearchResults/ShowSearchedUser/ShowSearchedUser.module.scss
- src/pages/SearchUsers/SearchResults/ShowSearchedUser/ShowSearchedUser.tsx
- src/pages/Station/CreateStation/CreateStation.tsx
- src/pages/Station/CreateStation/CreateStationBackground/CreateStationBackground.tsx
- src/pages/Station/CreateStation/CreateStationInfo/CreateStationInfo.tsx
- src/pages/Station/ShowStationsList/ShowStationList.tsx
- src/pages/Station/ShowStationsList/StationDisplay/StationDisplay.tsx
> Feat: background not complete

- src/pages/Home/MyStar.tsx
- src/pages/PageManagement/Pending.tsx
- 캐릭터 url설정
-  
- 
- 
- 
- 
- 
- 
-  
> Fix: character url

- src/pages/CharacterSettings/ProfileSetUp.tsx
- src/pages/Station/StationSlide/StationSlide.tsx
> 128 charactermove

- src/pages/Report/Report.tsx
- src/pages/Report/ReportList/ReportList.tsx
- src/pages/Report/ReportModal/ReportModal.module.scss
- src/pages/Report/ReportModal/ReportModal.tsx
- src/pages/Station/StationInside/StationInside.tsx
- src/pages/Station/StationSlide/StationSlide.tsx
> Feat: character server

- src/components/DeleteFriendModal/DeleteFriendModal.module.scss
- src/components/DeleteFriendModal/DeleteFriendModal.tsx
- src/pages/FriendsTab/FriendsTab.module.scss
- src/pages/FriendsTab/ShowFriendRequestsList/ShowFriendRequestsList.module.scss
- src/pages/FriendsTab/ShowFriendRequestsList/ShowFriendRequestsList.tsx
- src/pages/FriendsTab/ShowMyFriendsList/ShowMyFriendsList.module.scss
- src/pages/FriendsTab/ShowMyFriendsList/ShowMyFriendsList.tsx
- src/pages/FriendsTab/ShowMyRequestsList/ShowMyRequestsList.module.scss
- src/pages/FriendsTab/ShowMyRequestsList/ShowMyRequestsList.tsx
- src/pages/SearchUsers/SearchResults/SearchResults.tsx
- src/pages/SearchUsers/SearchResults/ShowSearchedUser/ShowSearchedUser.module.scss
- src/pages/SearchUsers/SearchResults/ShowSearchedUser/ShowSearchedUser.tsx
- src/pages/SearchUsers/SearchUsers.tsx
> 127 search page popup modify

- src/pages/SearchUsers/SearchResults/ShowSearchedUser/ShowSearchedUser.tsx
- src/pages/Station/CreateStation/CreateStation.tsx
- src/pages/Station/CreateStation/CreateStationBackground/CreateStationBackground.tsx
> Feat: create station complete

- src/App.tsx
- 초기화면에 스플래시 안뜸
-  
- 
- 
- 
- 
- 
- 
-  
> Fix: App.tsx

- src/functions/logInRequest.ts
- src/pages/CharacterSettings/CharacterSetUp.tsx
- src/pages/CharacterSettings/characterSetUpTab/FaceTab.tsx
- src/pages/CharacterSettings/characterSetUpTab/ItemTab.tsx
- src/pages/CharacterSettings/characterSetUpTab/OutFitTab.tsx
- src/pages/LogIn/LogIn.tsx
- src/pages/PageManagement/Pending.module.scss
- 버그픽스~
-  
- 
- 
- 
- 
- 
- 
-  
> fix: kill bug

- src/pages/CharacterSettings/characterSetUpTab/FaceTab.tsx
- src/pages/CharacterSettings/characterSetUpTab/ItemTab.tsx
- src/pages/CharacterSettings/characterSetUpTab/OutFitTab.tsx
- 리렌더링 계속되는 오류 고침
-  
- 
-
- 
- 
-
- 
-  
> Fix: rerender

- src/pages/Station/CreateStation/CreateStation.tsx
- src/pages/Station/CreateStation/CreateStationBackground/CreateStationBackground.module.scss
- src/pages/Station/CreateStation/CreateStationInfo/CreateStationInfo.module.scss
- src/pages/Station/ShowStationsList/ShowStationList.module.scss
- src/pages/Station/ShowStationsList/StationDisplay/StationDisplay.tsx
> Feat: station complete

- src/pages/CharacterSettings/BackgroundSetUp.tsx
- src/pages/CharacterSettings/backgroundSetUp.module.scss
- src/pages/Station/StationInside/CharacterReport/CharacterReport.module.scss
- src/pages/Station/StationInside/CharacterReport/CharacterReport.tsx
- src/pages/Station/StationInside/StationInside.tsx
-  친구 리포트 보기
- 
- 친구별 방문
- 
- 
-  
> 157 characterreport

- src/pages/Station/CreateStation/CreateStation.tsx
> Feat: change name

- src/App.tsx
- src/pages/Station/Station.tsx
- src/pages/Station/StationInside/StationInside.tsx
- src/pages/Station/StationSetting/StationBackgroundSetting.tsx
- src/pages/Station/StationSetting/StationSetting.tsx
- src/pages/Station/StationSlide/StationSlide.tsx
> Feat: add pages

- src/pages/FriendsTab/FriendsTab.tsx
- src/pages/FriendsTab/ReceiveSignalPopup/ReceiveSignalPopup.module.scss
- src/pages/FriendsTab/ReceiveSignalPopup/ReceiveSignalPopup.tsx
- src/pages/FriendsTab/SendSignalPopup/SendSignalPopup.tsx
- src/pages/Station/ShowStationsList/ShowStationList.tsx
- src/pages/Station/ShowStationsList/StationDisplay/StationDisplay.tsx
> Feat: Signal complete

- .github/workflows/build-deploy.yml
- src/functions/loadImage.ts
- src/pages/CharacterSettings/BackgroundSetUp.tsx
- src/pages/FriendsTab/ShowMyFriendsList/ShowMyFriendsList.tsx
- src/pages/Home/FriendStar.tsx
- src/pages/LogIn/LogIn.tsx
- src/pages/Station/StationInside/CharacterReport/CharacterReport.tsx
- yml 파일 변경
- 친구 별 추가
- 캐릭터 설정 후 대기화면 안뜨는 오류 수정
- 
- 
- 
- 
- 
-  
> Feat: Friend Star

- src/pages/Setting/ProfileSetting/ProfileSetting.tsx
> delete user Id

- src/pages/FriendsTab/FriendsTab.tsx
- src/pages/FriendsTab/ReceiveSignalPopup/ReceiveSignalPopup.tsx
> 173 check issue

- src/pages/FriendsTab/ReceiveSignalPopup/ReceiveSignalPopup.tsx
> Feat: modify

- src/pages/FriendsTab/ReceiveSignalPopup/ReceiveSignalPopup.module.scss
> Feat: fix animation

- package-lock.json
- package.json
- src/api/axiosInstance.ts
-  api 폴더 내 파일 추가
- 
- 
- 
- 
-  
> Feat: Adding axiosInstance.ts

- src/interfaces/Interfaces.ts
- src/pages/FriendsTab/FriendsTab.tsx
- src/pages/FriendsTab/ShowMyFriendsList/ShowMyFriendsList.tsx
- src/pages/FriendsTab/ShowMyRequestsList/ShowMyRequestsList.tsx
- src/pages/FriendsTab/ShowTotalFriendsList/ShowTotalFriendsList.tsx
- src/pages/SearchUsers/RecentSearch/RecentSearch.tsx
- src/pages/SearchUsers/SearchResults/SearchResults.tsx
- src/pages/SearchUsers/SearchResults/ShowSearchedUser/ShowSearchedUser.tsx
- src/pages/SearchUsers/SearchUsers.tsx
- src/pages/Station/CreateStation/CreateStationInfo/CreateStationInfo.tsx
- src/pages/Station/ShowStationsList/ShowStationList.tsx
-  인터페이스 관련 코드 최적화
- 
- 
- 
- 
-  
> Feat: optimizing code about interface

- src/pages/Station/ShowStationsList/ShowStationList.tsx
> Fix: change PATCH -> GET

- src/functions/axiosRequest.ts
- src/pages/CharacterSettings/ProfileSetUp.tsx
- src/pages/FriendsTab/FriendsTab.tsx
- src/pages/FriendsTab/ShowMyFriendsList/ShowMyFriendsList.tsx
- src/pages/Home/FriendStar.tsx
- src/pages/LogIn/KakaoLogin.tsx
- src/pages/LogIn/LogIn.tsx
- src/pages/LogIn/NaverLogin.tsx
- src/pages/Report/Report.tsx
- src/pages/SearchUsers/SearchUsers.tsx
- src/pages/Setting/PersonalSetting/PersonalSetting.tsx
- src/pages/Station/CreateStation/CreateStation.tsx
- src/pages/Station/ShowStationsList/ShowStationList.tsx
- src/pages/Station/StationInside/CharacterReport/CharacterReport.tsx
- src/pages/Station/StationInside/CharacterReport/MyReport.tsx
- src/pages/Station/StationInside/StationInside.tsx
- src/pages/Station/StationInside/StationReport/StationReport.tsx
- export const axiosRequest = async <T>(
requestPoint: string,
method: Methods,
body: object | null
): Promise<{ data: T; status: number; message?: string }> => {
try {
const config: AxiosRequestConfig = {
method,
url: requestPoint,
data: body,
};
const response = await axiosInstance(config);
return {
data: response.data,
status: response.status,
message: response.data?.message,
};
} catch (error) {
console.error("API 요청 실패:", error);
throw error;
}
};
> Fix: change axiosRequest

- src/pages/CharacterSettings/ProfileSetUp.tsx
- src/pages/Home/FriendStar.tsx
> 198 fix axios

- src/pages/Station/ShowStationsList/ShowStationList.tsx
- src/pages/Station/StationInside/useStationInsideQuery.ts
-  정거장 정렬기준 정보 저장
- 
- 
- 
- 
-  
> Feat: sort criteria remember

- src/pages/FriendStar/FriendReport/FriendReport.module.scss
- src/pages/FriendStar/FriendReport/FriendReport.tsx
- src/pages/FriendStar/FriendStar.tsx
- src/pages/FriendStar/ReportList/FriendReportList.module.scss
- src/pages/FriendStar/ReportList/FriendReportList.tsx
- src/pages/FriendStar/ReportModal/FriendReportModal.tsx
- src/pages/FriendStar/ReportModal/ReportModal.module.scss
- src/pages/FriendStar/SearchReport/SearchReport.module.scss
- src/pages/FriendStar/SearchReport/SearchReport.tsx
- src/pages/FriendStar/SearchReportsBar/SearchReportsBar.module.scss
- src/pages/FriendStar/SearchReportsBar/SearchReportsBar.tsx
> Feat: friendReport

- src/pages/CharacterSettings/BackgroundSetUp.tsx
- src/pages/CharacterSettings/ProfileSetUp.tsx
- src/pages/CharacterSettings/hooks/useGenerateCharacterImageMutation.ts
- src/pages/CharacterSettings/hooks/useIdCheckQuery.ts
- src/pages/CharacterSettings/hooks/useSignupMutation.ts
- src/pages/CharacterSettings/hooks/useUserCharacterQuery.ts
> CharacterSettings API통신 tanStack query로 변경

- src/pages/FriendsTab/FriendsTab.tsx
- src/pages/FriendsTab/ReceiveSignalPopup/ReceiveSignalPopup.module.scss
- src/pages/FriendsTab/ReceiveSignalPopup/ReceiveSignalPopup.tsx
> 212 signalbox disappear issue

- src/pages/FriendStar/FriendReport/FriendReport.tsx
> 친구별 리포트 검색기록 추가

- src/pages/Setting/PersonalSetting/PersonalSetting.tsx
- src/pages/Station/StationInside/StationReport/StationReport.tsx
> 로그아웃, 정거장 뒤로가기 추가

- src/components/ConfirmModal/ConfirmModal.module.scss
- src/components/ConfirmModal/ConfirmModal.tsx
- src/pages/Setting/PersonalSetting/PersonalSetting.tsx
> 로그아웃 모달 추가

- src/assets/ImageData/BackgroundImage.ts
- src/pages/CharacterSettings/BackgroundSetUp.tsx
- src/pages/CharacterSettings/ProfileSetUp.tsx
- src/pages/CharacterSettings/backgroundSetUp.module.scss
- src/pages/CharacterSettings/backgroundTab.module.scss
- src/pages/CharacterSettings/profileSetUp.module.scss
- src/pages/FriendStar/FriendStar.tsx
- src/store/useCharacterStore.ts
> 229 fix error

- src/components/ConfirmModal/ConfirmModal.module.scss
- src/components/ConfirmModal/DeleteAccountModal.tsx
- src/pages/Setting/PersonalSetting/PersonalSetting.tsx
- src/pages/Station/CreateStation/CreateStation.tsx
- src/pages/Station/CreateStation/useCreateStationMutation.ts
- src/pages/Station/ShowStationsList/ShowStationList.tsx
- src/pages/Station/ShowStationsList/StationListBottomSheet/StationListBottomSheetOpen.tsx
- src/pages/Station/StationSetting/StationBackgroundSetting.tsx
> 탈퇴하기 모달, 정거장 배경 변경

- .github/workflows/prod-deploy.yml
- .github/workflows/test-deploy.yml
- src/pages/CharacterSettings/BackgroundSetUp.tsx
- src/pages/CharacterSettings/CharacterSetUp.tsx
- src/pages/CharacterSettings/ProfileSetUp.tsx
- src/pages/PageManagement/Pending.tsx
- src/pages/SplashScreen/Splash.module.scss
- src/pages/SplashScreen/Splash.tsx
- test 배포 생성
- 앞으로 test 브랜치에서 분기해서 test 브랜치에 머지 바람
- https://test.pleiades.com 을 통해 test 웹 진입가능
- 
- 
- 
- 
- 
-  
> File clean

- .claude/settings.local.json
- src/pages/PageManagement/AuthHandler.tsx
- src/pages/Station/StationInside/DraggableMember.tsx
- src/pages/Station/StationInside/StationInside.module.scss
- src/pages/Station/StationInside/StationInside.tsx
- src/utils/hashUtils.ts
- 로컬 개발모드 시 AuthHandler 비활성화
- 정거장에 캐릭터 움직이는 기능
- 
- 몰라잉
- 
- 
- 없어잉
- 
-  
> feat: move character position, dev mode

- src/App.tsx
- src/pages/Market/Market.tsx
- src/pages/Market/MarketHome.tsx
> change route graph to use bottombar in my-item-sell screen

- src/App.tsx
- src/pages/LandingPage/LandingPage.module.scss
- src/pages/LandingPage/LandingPage.tsx
- src/pages/PrivacyPage/PrivacyPage.tsx
- src/pages/TermsPage/TermsPage.tsx
랜딩페이지 및 이용약관, 개인정보처리방침 페이지 추가~
> Add landing pages and implement public routing

- src/App.tsx
- src/assets/pleiadesBackArrow.svg
- src/pages/Market/MarketHome.module.scss
- src/pages/Market/MarketHome.tsx
- src/pages/Market/MyItemPriceCheck/MyItemPriceCheck.module.scss
- src/pages/Market/MyItemPriceCheck/MyItemPriceCheck.tsx
- src/pages/Market/MyItemSell/MyItemSell.module.scss
- src/pages/Market/MyItemSell/MyItemSell.tsx
- src/pages/Market/MyItemSell/component/SellItemModal.module.scss
- src/pages/Market/MyItemSell/component/SellItemModal.tsx
> my item sell

- src/pages/LandingPage/LandingPage.tsx
> fix: miss meta tag fix

- src/pages/Station/StationInside/DraggableMember.tsx
> fix: add meta tag in LandingPage 25.10.04 01:30

- src/pages/Station/ShowStationsList/ShowStationList.module.scss
- src/pages/Station/ShowStationsList/ShowStationList.tsx
- src/pages/Station/ShowStationsList/StationBottomSheetContent/StationBottomSheetContent.tsx
> feat(station): Replace mock data with API call for station list
